[build]
command = "npm install && npm run build"
publish = "apps/web/.next"

[build.environment]
NEXT_TELEMETRY_DISABLED = "1"
NODE_VERSION = "20"
HUSKY = "0"

[[plugins]]
package = "@netlify/plugin-nextjs"
